# Generated by Django 5.2.5 on 2026-02-28 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=200)),
                ('university_short', models.CharField(max_length=50)),
                ('pattern_year', models.CharField(max_length=4)),
                ('stream', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('grading_scale', models.DecimalField(choices=[('10.0', '10.0 Scale'), ('7.0', '7.0 Scale'), ('4.0', '4.0 Scale')], decimal_places=1, max_digits=3)),
                ('total_semesters', models.IntegerField(choices=[(6, '6 Semesters'), (8, '8 Semesters'), (10, '10 Semesters')])),
                ('ai_analysis', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField()),
                ('sgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('credits', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['semester_number'],
            },
        ),
    ]
