# Generated by Django 5.2.5 on 2026-02-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprofile',
            name='ai_improvement_advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
