# Generated by Django 5.2.5 on 2026-02-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_completed_tasks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('stream', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('average_salary', models.CharField(max_length=100)),
                ('growth_rate', models.CharField(max_length=50)),
                ('education_required', models.CharField(max_length=200)),
                ('key_skills', models.TextField(help_text='Comma-separated skills')),
                ('job_outlook', models.TextField()),
                ('industries', models.TextField(help_text='Comma-separated industries')),
            ],
        ),
        migrations.CreateModel(
            name='CareerJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('step_title', models.CharField(max_length=200)),
                ('step_description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('prerequisites', models.TextField(blank=True)),
                ('outcomes', models.TextField()),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_steps', to='accounts.careerpath')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='CareerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('importance', models.CharField(choices=[('essential', 'Essential'), ('important', 'Important'), ('helpful', 'Helpful')], max_length=20)),
                ('learn_time', models.CharField(max_length=100)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='accounts.careerpath')),
            ],
        ),
    ]
