# Generated by Django 5.2.5 on 2026-03-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='quiz',
            name='pattern',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='stream',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='year',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
