# Generated by Django 5.2.5 on 2026-02-28 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('total_papers_uploaded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_repeated_topics', models.JSONField(default=list, help_text='List of topics with frequency data')),
                ('high_probability_topics', models.JSONField(default=list, help_text='Topics likely to appear in next exam')),
                ('chapter_weightage', models.JSONField(default=list, help_text='Chapter-wise marks distribution')),
                ('question_pattern', models.JSONField(default=dict, help_text='Question pattern analysis')),
                ('predicted_questions', models.JSONField(default=list, help_text='AI predicted questions')),
                ('study_priority_list', models.JSONField(default=list, help_text='Prioritized study topics')),
                ('quick_insights', models.JSONField(default=list, help_text='Quick insights from analysis')),
                ('raw_ai_response', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_analyzer.examsubject')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exam_papers/')),
                ('year', models.IntegerField()),
                ('extracted_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_analyzer.examsubject')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
